# Required input
WorkDir=/path/to/working/directory
MDPFile=/path/to/mdp/files/directory
Structure=/path/to/simulated/structure/directory
GMX=gmx_2021.2
MartiniFiles=/path/to/martini_v300
WaterBoxFile=/path/to/equilibrated/water/box/water.gro
CreateVirtFile=/path/to/create_goVirt.py
ContactMap=/path/to/simulated/molecule/contact/map/directory



		###################################################################################################
		#################################### System Construction ##########################################
		###################################################################################################


# Note: the contact map for each single simulated molecule was generated by the following web-server: http://info.ifpan.edu.pl/~rcsu/rcsu/index.html

# Generate molecule topologies
# Leptin (In the 3:3 leptin-LR (PDB ID: 8AVF), leptin molecules' chain ids are designated 'A', 'C', 'E')
for i in A C E 
do
	mkdir $WorkDir/Chain${i}Topology
	cd $WorkDir/Chain${i}Topology
	
	martinize2 -f $Structure/Chain$i.pdb -o $WorkDir/Chain${i}Topology/chain$i.top -x $WorkDir/Chain${i}Topology/Chain$i.pdb -dssp mkdssp -p backbone -ff martini3001 -govs-include -govs-moltype Chain${i} -scfix -cys auto

	python3 $CreateVirtFile -s $WorkDir/Chain${i}Topology/Chain$i.pdb -f $ContactMap/Chain${i}/*/*/Chain${i}.map --moltype Chain${i} --go_eps 12.0 --Natoms 321 --missres 21

done


# LR (In the 3:3 leptin-LR (PDB ID: 8AVF), leptin molecules' chain ids are designated 'B', 'D', 'F')
for i in B D F
do
	mkdir $WorkDir/Chain${i}Topology
	cd $WorkDir/Chain${i}Topology
	
	martinize2 -f $Structure/Chain$i.pdb -o $WorkDir/Chain${i}Topology/chain$i.top -x $WorkDir/Chain${i}Topology/Chain$i.pdb -dssp mkdssp -p backbone -ff martini3001 -govs-include -govs-moltype Chain${i} -scfix -cys auto -nter NH2-ter -cter COOH-ter
	
	python3 $CreateVirtFile -s $WorkDir/Chain${i}Topology/Chain$i.pdb -f $WorkDir/ContactMap/Chain${i}/*/*/Chain${i}.map --moltype Chain${i} --go_eps 12.0 --Natoms 1465 --missres 235
	
done	


# Generate system protein topology
mkdir $WorkDir/Generate_CG_Topology
cd $WorkDir/Generate_CG_Topology

for f in $WorkDir/Chain*Topology/Chain*.pdb
do
	(cat "${f}"; echo) >> $WorkDir/Generate_CG_Topology/Leptin_LR_complex.pdb
done
	

cd $WorkDir/Generate_CG_Topology

cp $MartiniFiles/martini_v3.0.0* $WorkDir/Generate_CG_Topology

for i in A B C D E F 
do
	cp $WorkDir/Chain${i}Topology/Chain$i.itp $WorkDir/Generate_CG_Topology
	cp $WorkDir/Chain${i}Topology/chain_$i.ssd $WorkDir/Generate_CG_Topology
	cp $WorkDir/Chain${i}Topology/Chain${i}_* $WorkDir/Generate_CG_Topology
done

cp $WorkDir/ChainATopology/*.map $WorkDir/Generate_CG_Topology


# Create BB-part-def_VirtGoSites.itp and go-table_VirtGoSites.itp file 
for i in A B C D E F 
do
	echo "#include \"Chain${i}_BB-part-def_VirtGoSites.itp\"" >> $WorkDir/Generate_CG_Topology/BB-part-def_VirtGoSites.itp
	echo "#include \"Chain${i}_go-table_VirtGoSites.itp\"" >> $WorkDir/Generate_CG_Topology/go-table_VirtGoSites.itp
done

# Modify martini topology file
sed -i "s/\[ nonbond_params \]/\#ifdef GO_VIRT\n\#include \"BB-part-def_VirtGoSites.itp\"\n\#endif\n\n\[ nonbond_params \]/" $WorkDir/Generate_CG_Topology/martini_v3.0.0.itp

echo -e "\n#ifdef GO_VIRT \n#include \"go-table_VirtGoSites.itp\"\n#endif" >> $WorkDir/Generate_CG_Topology/martini_v3.0.0.itp

# Create system topology file
echo "#define GO_VIRT
#include \"martini_v3.0.0.itp\"
#include \"martini_v3.0.0_ions_v1.itp\"
#include \"martini_v3.0.0_solvents_v1.itp\"
#include \"ChainA.itp\"
#include \"ChainB.itp\"
#include \"ChainC.itp\"
#include \"ChainD.itp\"
#include \"ChainE.itp\"
#include \"ChainF.itp\"

[ system ]
Title of the system in water

[ molecules ]
ChainA    1
ChainB    1
ChainC    1
ChainD    1
ChainE    1
ChainF    1 " > $WorkDir/Generate_CG_Topology/system.top


#Vaccum energy minimization
mkdir $WorkDir/VaccumEM
cd $WorkDir/VaccumEM

$GMX editconf -f $WorkDir/Generate_CG_Topology/Leptin_LR_complex.pdb -d 2.5 -bt dodecahedron -o $WorkDir/VaccumEM/Complex_box.pdb

$GMX grompp -f $MDPFile/minimization.mdp -c $WorkDir/VaccumEM/Complex_box.pdb -p $WorkDir/Generate_CG_Topology/system.top -r $WorkDir/VaccumEM/Complex_box.pdb -o $WorkDir/VaccumEM/em.tpr

srun $GMX mdrun -s $WorkDir/VaccumEM/em.tpr -deffnm VaccumEM


# Building simulation box
mkdir $WorkDir/Simulation_box
cd $WorkDir/Simulation_box

# Solvation
$GMX solvate -cp $WorkDir/VaccumEM/VaccumEM.gro -cs $WaterBoxFile -radius 0.21 -o $WorkDir/Simulation_box/solvate.gro -p $WorkDir/Generate_CG_Topology/system.top

$GMX grompp -f $MDPFile/ions.mdp -c $WorkDir/Simulation_box/solvate.gro -r $WorkDir/Simulation_box/solvate.gro -p $WorkDir/Generate_CG_Topology/system.top -o $WorkDir/Simulation_box/ions.tpr 

echo "W" | $GMX genion -s $WorkDir/Simulation_box/ions.tpr -o $WorkDir/Simulation_box/solvate_ions.gro -p $WorkDir/Generate_CG_Topology/system.top -pname NA -nname CL -neutral -conc 0.15 


# Simulated molecules + solvent energy minimization
mkdir $WorkDir/EM
cd $WorkDir/EM

$GMX grompp -f $MDPFile/minimization.mdp -p $WorkDir/Generate_CG_Topology/system.top -c $WorkDir/Simulation_box/solvate_ions.gro -r $WorkDir/Simulation_box/solvate_ions.gro -o $WorkDir/EM/em.tpr -maxwarn 1 

srun $GMX mdrun -s $WorkDir/EM/em.tpr -deffnm EM


		###################################################################################################
		######################################### Equilibrations ##########################################
		###################################################################################################
		
		
# Multiple independent simulations: Each simulation was initiated with a random seed for initial velocity in the equilibration simulation with a time step of 2fs.

# Create separate directory for each independent simulation

for i in 1 2 3 4 5
do 
	mkdir $WorkDir/Rep$i 
done


# Equilibration execution using a time step of 2fs
for i in 1 2 3 4 5
do
	cd $WorkDir/Rep$i
	mkdir $WorkDir/Rep$i/npt_2fs
	cd $WorkDir/Rep$i/npt_2fs
	
	$GMX grompp -f $MDPFile/npt_2fs_systemCoupl.mdp -p $WorkDir/Generate_CG_Topology/system.top -c $WorkDir/EM/EM.gro -r $WorkDir/EM/EM.gro -o $WorkDir/Rep$i/npt_2fs/npt2fs.tpr
	
done	


# Executing mdrun
for i in 1 2 3 4 5 
do	
	cd $WorkDir/Rep$i/npt_2fs
	srun $GMX mdrun -s $WorkDir/Rep$i/npt_2fs/npt2fs.tpr -deffnm NPT2fs
done



# Equilibration execution using a time step of 10fs
for i in 1 2 3 4 5 
do
	cd $WorkDir/Rep$i
	mkdir $WorkDir/Rep$i/npt_10fs
	cd $WorkDir/Rep$i/npt_10fs
	
	$GMX grompp -f $MDPFile/npt_10fs_systemCoupl.mdp -p $WorkDir/Generate_CG_Topology/system.top -c $WorkDir/Rep$i/npt_2fs/NPT2fs.gro -r $WorkDir/Rep$i/npt_2fs/NPT2fs.gro -o $WorkDir/Rep$i/npt_10fs/npt10fs.tpr
	
done	


# Executing mdrun
for i in 1 2 3 4 5 
do	
	cd $WorkDir/Rep$i/npt_10fs
	srun $GMX mdrun -s $WorkDir/Rep$i/npt_10fs/npt10fs.tpr -deffnm NPT10fs
done


# Equilibration execution using a time step of 20fs
for i in 1 2 3 4 5 
do
	cd $WorkDir/Rep$i
	mkdir $WorkDir/Rep$i/npt_20fs
	cd $WorkDir/Rep$i/npt_20fs
	
	$GMX grompp -f $MDPFile/npt_20fs_systemCoupl.mdp -p $WorkDir/Generate_CG_Topology/system.top -c $WorkDir/Rep$i/npt_10fs/NPT10fs.gro -r $WorkDir/Rep$i/npt_10fs/NPT10fs.gro -o $WorkDir/Rep$i/npt_20fs/npt20fs.tpr 
	
done	


# Executing mdrun
for i in 1 2 3 4 5 
do	
	cd $WorkDir/Rep$i/npt_20fs
	srun $GMX mdrun -s $WorkDir/Rep$i/npt_20fs/npt20fs.tpr -deffnm NPT20fs
done




		###################################################################################################
		########################################### Production ############################################
		###################################################################################################

for i in 1 2 3 4 5 
do
	cd $WorkDir/Rep$i
	mkdir $WorkDir/Rep$i/MD
	cd $WorkDir/Rep$i/MD
	
	$GMX grompp -f $MDPFile/prod_systemCoupl.mdp -p $WorkDir/Generate_CG_Topology/system.top -c $WorkDir/Rep$i/npt_20fs/NPT20fs.gro -r $WorkDir/Rep$i/npt_20fs/NPT20fs.gro -o $WorkDir/Rep$i/MD/md.tpr 
	
done	

# Executing mdrun on parallel
srun $GMX mdrun -s md.tpr -deffnm MD -multidr $WorkDir/Rep*/MD














